"""End-to-end API tests for the doctrine catalogue + doctrine-sourced queries,
against the committed demo doctrine fixture."""

from __future__ import annotations

import json
from pathlib import Path

from tests.conftest import GATED_HEADERS, UNGATED_HEADERS

DATA_DEMO = Path(__file__).resolve().parent.parent / "data_demo"
DEMO_DOCTRINES = json.loads((DATA_DEMO / "doctrine_definitions_api.json").read_text())


def _identity(fit: dict) -> tuple[str, str, str, str]:
    return (fit["doctrine"], fit["role"], fit["ship_type"], fit["fit_name"])


def _tier_count(fit: dict, tier: str) -> int:
    key = f"level_{tier}"
    return sum(
        1 for pack in fit["skillpacks"].values() for s in pack if s[key] > 0
    )


# A fit known to have skills required at both tiers — first by identity order.
FIRST_FIT = sorted(DEMO_DOCTRINES, key=_identity)[0]


def _ref(fit: dict, tier: str) -> dict:
    return {
        "doctrine": fit["doctrine"],
        "role": fit["role"],
        "ship_type": fit["ship_type"],
        "fit_name": fit["fit_name"],
        "tier": tier,
    }


# --- catalogue ---------------------------------------------------------------


def test_doctrines_gated(client):
    assert client.get("/api/doctrines", headers=UNGATED_HEADERS).status_code == 403


def test_doctrines_shape_and_sort(client):
    body = client.get("/api/doctrines", headers=GATED_HEADERS).json()
    assert body["snapshot_version"] == 1
    fits = body["fits"]
    assert len(fits) == len(DEMO_DOCTRINES)
    # Sorted by the identity tuple.
    got = [(f["doctrine"], f["role"], f["ship_type"], f["fit_name"]) for f in fits]
    assert got == sorted(got)
    # Counts match the fixture (all demo doctrine skills resolve in the catalogue).
    first = next(
        f
        for f in fits
        if (f["doctrine"], f["role"], f["ship_type"], f["fit_name"]) == _identity(FIRST_FIT)
    )
    assert first["yellow_skill_count"] == _tier_count(FIRST_FIT, "yellow")
    assert first["green_skill_count"] == _tier_count(FIRST_FIT, "green")
    assert first["green_skill_count"] >= first["yellow_skill_count"]


# --- doctrine query ----------------------------------------------------------


def test_query_by_doctrine_ref(client):
    resp = client.post(
        "/api/query", json={"doctrine": _ref(FIRST_FIT, "yellow")}, headers=GATED_HEADERS
    )
    assert resp.status_code == 200
    body = resp.json()
    assert "rows" in body and "totals" in body
    # Provenance echoed back for the results header.
    assert body["doctrine"] == {
        **_ref(FIRST_FIT, "yellow"),
        "skill_count": _tier_count(FIRST_FIT, "yellow"),
    }


def test_doctrine_green_is_stricter_than_yellow(client):
    y = client.post(
        "/api/query", json={"doctrine": _ref(FIRST_FIT, "yellow")}, headers=GATED_HEADERS
    ).json()
    g = client.post(
        "/api/query", json={"doctrine": _ref(FIRST_FIT, "green")}, headers=GATED_HEADERS
    ).json()
    # Green requires more, so it can never match more characters than yellow.
    assert (
        g["totals"]["total_matching_characters"]
        <= y["totals"]["total_matching_characters"]
    )


def test_manual_query_has_no_doctrine_field(client):
    common = DEMO_DOCTRINES[0]["skillpacks"]["[Autogenerated Required Skills]"][0]["skill_id"]
    resp = client.post(
        "/api/query",
        json={"query": {"kind": "skill", "skill_id": common, "min_level": 1}},
        headers=GATED_HEADERS,
    )
    assert resp.status_code == 200
    assert resp.json()["doctrine"] is None


def test_unknown_doctrine_ref_422(client):
    bad = {**_ref(FIRST_FIT, "yellow"), "fit_name": "No Such Fit"}
    resp = client.post("/api/query", json={"doctrine": bad}, headers=GATED_HEADERS)
    assert resp.status_code == 422


def test_query_requires_exactly_one_of_query_or_doctrine(client):
    assert client.post("/api/query", json={}, headers=GATED_HEADERS).status_code == 422


# --- CSV export with d= ------------------------------------------------------


def test_csv_export_by_doctrine(client):
    from app.queries.doctrine import DoctrineRef, encode_doctrine_ref

    d = encode_doctrine_ref(DoctrineRef.model_validate(_ref(FIRST_FIT, "yellow")))
    resp = client.get(f"/api/query/export.csv?d={d}", headers=GATED_HEADERS)
    assert resp.status_code == 200
    assert resp.headers["content-type"].startswith("text/csv")
    lines = resp.text.splitlines()
    # Provenance metadata line, then the normal column header.
    assert lines[0].startswith("# Doctrine:")
    assert FIRST_FIT["doctrine"] in lines[0]
    assert lines[1].split(",")[0] == "user_name"


def test_csv_export_bad_d_422(client):
    resp = client.get("/api/query/export.csv?d=!!!", headers=GATED_HEADERS)
    assert resp.status_code == 422
